git branch -D asan-fixes
git branch -D delay-by-freq
git branch -D final-fx
git branch -D fm3-abs
git branch -D fpuguard-472
git branch -D fx-flanger
git branch -D fx-panels-3
git branch -D fx-panels-take-2
git branch -D layout-redux
git branch -D lfo-skeleton
git branch -D matrix-438
git branch -D matrix-445
git branch -D matrix-module
git branch -D mixer-443
git branch -D mixer-layout
git branch -D mixer-modulation
git branch -D phaser
git branch -D poly-fx
git branch -D poly-treemonster
git branch -D reverb2
git branch -D ringmod
git branch -D steve-fixes-1
git branch -D thursday-stuff
git branch -D tweaks
git branch -D various
git branch -D vcf-ws-stereo
git branch -D vcf-ws-tweaks
git branch -D vco-crash
git branch -D vco-more-440
git branch -D vocoder-etc
